# Generated by Django 4.1.1 on 2023-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe', '0002_alter_item_options_remove_item_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
