# Generated by Django 4.1.1 on 2023-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe', '0003_item_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=300),
        ),
    ]
